<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 20.07.2017
 * Time: 14:19
 */
class SuperUser extends User implements ISuperUser{
    public $role;
    public static $count =0;

    public function __construct($name, $login, $password, $role)
    {
        parent::__construct($name, $login, $password);
        $this->role = $role;
        ++self::$count;
        --parent::$count;
    }

    public function showInfo(){
        parent::showInfo(); // TODO: Change the autogenerated stub
        echo ' Role: ' . $this->role . '<br>';
    }

    function getInfo(){
        $arr = array();
        foreach($this as $name => $value){
            $arr[$name] = $value;
        }
        return $arr;
//        return (array)$this;
    }

}